update binaries

diff --git a/bin/display b/bin/display
--- a/bin/display
+++ b/bin/display
@@ -58,6 +58,11 @@ case $mode in
     killall -q polybar
 
     ;;
+*)
+    echo 'Invalid ID'
+    exit 1
+
+    ;;
 
 esac
 
